### ISSUE TITLE
Runtime prompt modification

### ISSUE THREAD

**Issue by david-andrew** [jataware/archytas#5]
## Problem
Presently, the prompts generated for an agent are static, and based solely off the docstrings/type signatures of the tools passed into the ReActAgent class. E.g.

```
from archytas.tools import PythonTool
from archytas.react import ReActAgent

agent = ReActAgent(tools=[PythonTool], verbose=True)
print(agent.prompt)
```

Which generates the following (abridged) prompt:
```
You are the ReAct (Reason & Action) assistant. ...

# Tools
You have access to the following tools which can help you in your job:

PythonTool (class):
    Tool for running python code. If the user asks you to write code, you can run it here.

    methods:
        run:
            Runs python code in a python environment.

            The environment is persistent between runs, so any variables created will be available in subsequent runs.
            The only visible effects of this tool are from output to stdout/stderr. If you want to view a result, you MUST print it.

            _input_: (str) The code to run
            _output_: (str) The stdout output of the code

ask_user:
    Ask the user a question and get their response. 

    You should ask the user a question if you do not have enough information to complete the task, and there is no suitable tool to help you.

    _input_: (str) The question to ask the user
    _output_: (str) The user's response

final_answer:
    the final_answer tool is used to indicate that you have completed the task. You should use this tool to communicate the final answer to the user.
    _input_: the final answer to the user's task

fail_task
    the fail_task tool is used to indicate that you have failed to complete the task. You should use this tool to communicate the reason for the failure to the user. Do not call this tool unless you have given a good effort to complete the task.
    _input_: the reason for the failure


<other prompt information...>
```

This prompt gets generated when the agent is instantiated, and there is no way to adjust it after the fact. For the `PythonTool` specifically, it would be useful to be able modify the description to indicate that prelude code was run or that extra local variables are available.

```
# make a tool instance with prelude code and variables
python = PythonTool(
    # code to run at the beginning
    prelude='import numpy as np\nfrom matplotlib import pyplot as plt',
    # variables to include in the environment 
    locals={'fib_n': fib_n, 'ModelSimulation': ModelSimulation, 'jackpot': jackpot, 'pyman': pyman},
)

agent = ReActAgent(tools=[python], verbose=True)
```

At present, there is no way to update the description for the PythonTool to reflect that the environment has extra variables, and has already run some code. It's also relevant to managing context for a given tool.

**There needs to be a good approach for adjusting the tool's prompt**

## Possible approaches
- method that the user can call any time that overwrites the current prompt. Perhaps the method gets attached to the `@tool`/`@toolset` wrappers that get generated, and attach a `_prompt_override` variable to the wrapper. 
  - The system prompt could be regenerated on every call to the OpenAI api, and if the `_prompt_override` variable is present, it is used instead of the generated prompt
  -  or an extra message gets inserted into the chat history that is sent to the LLM indicating the change.
- `@toolsets` could allow for an optional `generate_prompt` method that would be called when prompts are being generated, and override the default generated prompt for the toolset.

**Comment by mattprintz** [comment]
This issue was solved by adding the auto_context functionality.
